<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Practice" data-toc-modified-id="Practice-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Practice</a></span></li><li><span><a href="#Excercise" data-toc-modified-id="Excercise-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Excercise</a></span></li></ul></div>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
%matplotlib inline

In [2]:
df = pd.read_csv('homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

### Practice

In [3]:
#impute the median for the missing value
import math

median_bedrooms = math.floor(df.bedrooms.median())
df['bedrooms'] = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [4]:
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms', 'age']].values, df['price'])

LinearRegression()

In [5]:
m_i = reg.coef_
m_i

array([  112.06244194, 23388.88007794, -3231.71790863])

In [6]:
b = reg.intercept_
b

221323.0018654043

In [7]:
# coefficients
m_1 = 112.06244194
m_2 = 23388.88007794
m_3 = -3231.71790863

Predicting the price of a home that has:
    (3000 sqft of area, 3 bedrooms, 40 years old) and 
    (2500 sqft of area, 4 bedrooms, 5 years old)

In [8]:
reg.predict([[3000, 3, 40]])

array([498408.25158031])

In [9]:
y = m_1*3000 + m_2*3 + m_3*40 + b
y

498408.2515740243

In [10]:
reg.predict([[2500, 4, 5]])

array([578876.03748933])

In [11]:
y = m_1*2500 + m_2*4 + m_3*5 + b
y

578876.0374840144

### Excercise

Build an ML model for HR department that can help them decide salaries for future candidates. Predict salaries for the following candidates:

>2yr experience, 9 test score, 6 interview score

>12 yr experience, 10 test score, 10 interview score

In [12]:
df_hire = pd.read_csv('hiring.csv')
df_hire

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [13]:
#impute values for experience
from word2number import w2n

df_hire.experience = df_hire.experience.fillna('zero').apply(w2n.word_to_num)
df_hire

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [14]:
# impute mean for test scores
import math

mean_testscores = math.floor(df_hire['test_score(out of 10)'].mean())
df_hire['test_score(out of 10)'] = df_hire['test_score(out of 10)'].fillna(mean_testscores)
df_hire

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [15]:
df_hire.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   experience                  8 non-null      int64  
 1   test_score(out of 10)       8 non-null      float64
 2   interview_score(out of 10)  8 non-null      int64  
 3   salary($)                   8 non-null      int64  
dtypes: float64(1), int64(3)
memory usage: 384.0 bytes


In [22]:
# fitting the model

reg = linear_model.LinearRegression()
reg.fit(df_hire[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']].values, df_hire['salary($)'])

LinearRegression()

In [23]:
reg.predict([[2, 9, 6]])

array([53713.86677124])

In [24]:
reg.predict([[12, 10, 10]])

array([93747.79628651])

Predicted salary will increase the more 'senior' an interviewee is.

>Salary for 2 years, a score of 9 on the test, and a score of 6 for interviews is predicted to earn (USD 53,713)

>Salary for 12 years, a score of 10 on the test, and a score of 10 for interviews is predicted to earn (USD $93,747)