<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Practice" data-toc-modified-id="Practice-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Practice</a></span></li><li><span><a href="#Excercise" data-toc-modified-id="Excercise-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Excercise</a></span></li><li><span><a href="#Results" data-toc-modified-id="Results-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Results</a></span></li></ul></div>

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits=load_digits()

### Practice

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3, train_size=0.7)

In [17]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

C:\Users\Admin\anaconda3\envs\Udacity\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9592592592592593

In [18]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.987037037037037

In [20]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9740740740740741

In [21]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [22]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [23]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [24]:
get_score(LogisticRegression(), X_train, X_test, y_train, y_test)

C:\Users\Admin\anaconda3\envs\Udacity\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9592592592592593

In [25]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [36]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(class_weight='balanced', max_iter=10000), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [37]:
scores_l

[0.9282136894824707, 0.9398998330550918, 0.9165275459098498]

In [38]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [39]:
scores_rf

[0.9198664440734557, 0.9465776293823038, 0.9248747913188647]

In [41]:
from sklearn.model_selection import cross_val_score

cross_val_score(LogisticRegression(max_iter=10000), digits.data, digits.target)

array([0.925     , 0.87777778, 0.93871866, 0.93314763, 0.89693593])

In [42]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [43]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target)

array([0.91944444, 0.9       , 0.95543175, 0.95543175, 0.91086351])

In [44]:
cross_val_score(RandomForestClassifier(n_estimators=5), digits.data, digits.target)

array([0.85      , 0.78055556, 0.87465181, 0.90529248, 0.85236769])

In [45]:
cross_val_score(RandomForestClassifier(n_estimators=15), digits.data, digits.target)

array([0.9       , 0.89444444, 0.93871866, 0.94150418, 0.91922006])

In [46]:
cross_val_score(RandomForestClassifier(n_estimators=50), digits.data, digits.target)

array([0.93611111, 0.90277778, 0.94986072, 0.96657382, 0.92479109])

### Excercise

Use the iris dataset from sklearn library to run cross_val_score against the following methods to measure performance of each. Which model performs the best?

1. Logistic Regression
1. Support Vector Machine
3. Decision Tree
4. Random Forest

In [52]:
from sklearn.datasets import load_iris
iris = load_iris()

In [83]:
#Logistic Regression
score1 = cross_val_score(LogisticRegression(solver='lbfgs', class_weight='balanced', max_iter=200), iris.data, iris.target, cv=10)
np.mean(score1)

0.9733333333333334

In [84]:
#SVM
score2 = cross_val_score(SVC(kernel='poly', C=4, gamma='scale'), iris.data, iris.target, cv=10)
np.mean(score2)

0.9800000000000001

In [87]:
from sklearn import tree


#Decision Tree
score3 = cross_val_score(tree.DecisionTreeClassifier(criterion='entropy'), iris.data, iris.target, cv=10)
np.mean(score3)

0.96

In [88]:
#Random Forest

score4 = cross_val_score(RandomForestClassifier(n_estimators=40), iris.data, iris.target, cv=10)
np.mean(score4)

0.96

### Results

SVM > Logistic Regression > Decision Tree ~ Random Forest